pipeline {
    agent any
    tools {
        maven "maven_354"
        jdk "java_8"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
       stage('Result') {
            steps {
                    junit '**/target/surefire-reports/**/*.xml'
                }
        }

        stage('Sonar'){
                steps{
                     withSonarQubeEnv('sonarqube') {
                  sh "mvn package sonar:sonar"
            
                    }
                }
            }
        }
    }
}
