pipeline {
    agent any
    tools {
        maven "maven_354"
        jdk "java_8"
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Dmaven-test.failure.ignore test'
            }
        }
       stage('Result') {
            steps {
                    junit '**/target/surefire-reports/**/*.xml'
                }
        }

        stage('Sonar'){
                steps{
                     withSonarQubeEnv('sonarqube') {
                  sh "mvn package sonar:sonar -Dsonar.projectKey=com.orrius.example -Dsonar.projectName=com.orrius.example -Dsonar.projectVersion=${BUILD_NUMBER} -Dsonar.language=java -Dsonar.sources=src/ -Dsonar.sourcesEnconding=UTF-8 -Dsonar.java.binaries=target/classes -Dsonar.exclusions=src/test/**'"
            
                    }
                }
        }
    }
}
